// Actual display dimensions and source-preserving card viewports.
// Generated by scripts/frame-product-cards.mjs from the audited catalogue.
export type CataloguePhoto = { src: string; width: number; height: number; native?: boolean };

export const cataloguePhotos: Record<string, CataloguePhoto> = {
  "/gallery/st-werkz/travertine-compote.jpg": {
    "src": "/gallery/card-frames/travertine-compote.svg",
    "width": 736,
    "height": 625
  },
  "/gallery/accents-travertine-tray.jpg": {
    "src": "/gallery/accents-travertine-tray.jpg",
    "width": 736,
    "height": 912
  },
  "/gallery/accents-oblong-tray.jpg": {
    "src": "/gallery/accents-oblong-tray.jpg",
    "width": 736,
    "height": 981
  },
  "/gallery/clean/accents-round-tray.svg": {
    "src": "/gallery/clean/accents-round-tray.svg",
    "width": 584,
    "height": 244
  },
  "/gallery/accents-coaster-suite.jpg": {
    "src": "/gallery/card-frames/coaster-suite.svg",
    "width": 600,
    "height": 620
  },
  "/gallery/st-werkz/sage-onyx-coasters-a.jpg": {
    "src": "/gallery/st-werkz/sage-onyx-coasters-a.jpg",
    "width": 736,
    "height": 736
  },
  "/gallery/clean/accents-curved-canisters.svg": {
    "src": "/gallery/clean/accents-curved-canisters.svg",
    "width": 470,
    "height": 390
  },
  "/gallery/clean/accents-pedestal-bowl.svg": {
    "src": "/gallery/clean/accents-pedestal-bowl.svg",
    "width": 570,
    "height": 283
  },
  "/gallery/st-werkz/sage-onyx-pear-bowl.jpg": {
    "src": "/gallery/st-werkz/sage-onyx-pear-bowl.jpg",
    "width": 736,
    "height": 920
  },
  "/gallery/st-werkz/scalloped-onyx-bowl-a.jpg": {
    "src": "/gallery/st-werkz/scalloped-onyx-bowl-a.jpg",
    "width": 736,
    "height": 1022
  },
  "/gallery/accents-nero-disc-tray.jpg": {
    "src": "/gallery/accents-nero-disc-tray.jpg",
    "width": 700,
    "height": 700
  },
  "/gallery/st-werkz/portoro-bath-set.jpg": {
    "src": "/gallery/st-werkz/portoro-bath-set.jpg",
    "width": 600,
    "height": 600
  },
  "/gallery/st-werkz/travertine-vanity-gold.jpg": {
    "src": "/gallery/st-werkz/travertine-vanity-gold.jpg",
    "width": 600,
    "height": 600
  },
  "/gallery/st-werkz/travertine-bath-ensemble.jpg": {
    "src": "/gallery/st-werkz/travertine-bath-ensemble.jpg",
    "width": 736,
    "height": 1130
  },
  "/gallery/st-werkz/travertine-bath-seven.jpg": {
    "src": "/gallery/card-frames/travertine-bath-seven.svg",
    "width": 736,
    "height": 690
  },
  "/gallery/accents-travertine-bath.jpg": {
    "src": "/gallery/accents-travertine-bath.jpg",
    "width": 314,
    "height": 239,
    "native": true
  },
  "/gallery/accents-vessel-sink.jpg": {
    "src": "/gallery/card-frames/vessel-sink.svg",
    "width": 670,
    "height": 365
  },
  "/gallery/st-werkz/copper-vein-basin.jpg": {
    "src": "/gallery/card-frames/copper-vein-basin.svg",
    "width": 640,
    "height": 400
  },
  "/gallery/accents-coral-canister.jpg": {
    "src": "/gallery/accents-coral-canister.jpg",
    "width": 736,
    "height": 736
  },
  "/gallery/accents-scalloped-valet.jpg": {
    "src": "/gallery/accents-scalloped-valet.jpg",
    "width": 736,
    "height": 981
  },
  "/gallery/st-werkz/portoro-cylinder-cup.jpg": {
    "src": "/gallery/st-werkz/portoro-cylinder-cup.jpg",
    "width": 500,
    "height": 500
  },
  "/gallery/accents-nero-cylinder.jpg": {
    "src": "/gallery/accents-nero-cylinder.jpg",
    "width": 576,
    "height": 1024
  },
  "/gallery/clean/accents-tapered-vessel.svg": {
    "src": "/gallery/clean/accents-tapered-vessel.svg",
    "width": 660,
    "height": 837
  },
  "/gallery/st-werkz/banded-onyx-vase.jpg": {
    "src": "/gallery/st-werkz/banded-onyx-vase.jpg",
    "width": 735,
    "height": 981
  },
  "/gallery/st-werkz/portoro-baluster-vase.jpg": {
    "src": "/gallery/st-werkz/portoro-baluster-vase.jpg",
    "width": 736,
    "height": 981
  },
  "/gallery/st-werkz/terracotta-marble-urn.jpg": {
    "src": "/gallery/st-werkz/terracotta-marble-urn.jpg",
    "width": 736,
    "height": 736
  },
  "/gallery/st-werkz/live-edge-onyx-vessel.jpg": {
    "src": "/gallery/st-werkz/live-edge-onyx-vessel.jpg",
    "width": 736,
    "height": 736
  },
  "/gallery/st-werkz/onyx-chess-casket.jpg": {
    "src": "/gallery/st-werkz/onyx-chess-casket.jpg",
    "width": 736,
    "height": 981
  },
  "/gallery/st-werkz/nero-chess-set.jpg": {
    "src": "/gallery/st-werkz/nero-chess-set.jpg",
    "width": 736,
    "height": 736
  },
  "/gallery/clean/accents-travertine-candlesticks.svg": {
    "src": "/gallery/clean/accents-travertine-candlesticks.svg",
    "width": 660,
    "height": 922
  },
  "/gallery/clean/accents-bulbous-vessel.svg": {
    "src": "/gallery/clean/accents-bulbous-vessel.svg",
    "width": 660,
    "height": 859
  },
  "/gallery/accents-portoro-bookends.jpg": {
    "src": "/gallery/card-frames/portoro-bookends.svg",
    "width": 736,
    "height": 566
  },
  "/gallery/accents-desk-suite.jpg": {
    "src": "/gallery/accents-desk-suite.jpg",
    "width": 736,
    "height": 736
  },
  "/gallery/accents-nero-candles.jpg": {
    "src": "/gallery/accents-nero-candles.jpg",
    "width": 736,
    "height": 736
  },
  "/gallery/accents-hemisphere-candle.jpg": {
    "src": "/gallery/accents-hemisphere-candle.jpg",
    "width": 681,
    "height": 1024
  },
  "/gallery/accents-onyx-urns.jpg": {
    "src": "/gallery/accents-onyx-urns.jpg",
    "width": 735,
    "height": 832
  },
  "/gallery/st-werkz/tall-noir-vase.jpg": {
    "src": "/gallery/st-werkz/tall-noir-vase.jpg",
    "width": 736,
    "height": 1104
  },
  "/gallery/st-werkz/pair-stone-pedestals.jpg": {
    "src": "/gallery/st-werkz/pair-stone-pedestals.jpg",
    "width": 736,
    "height": 1226
  },
  "/gallery/st-werkz/travertine-drum-side.jpg": {
    "src": "/gallery/st-werkz/travertine-drum-side.jpg",
    "width": 736,
    "height": 1104
  },
  "/gallery/st-werkz/travertine-cone-pedestal.jpg": {
    "src": "/gallery/st-werkz/travertine-cone-pedestal.jpg",
    "width": 736,
    "height": 1104
  },
  "/gallery/st-werkz/travertine-c-table.jpg": {
    "src": "/gallery/st-werkz/travertine-c-table.jpg",
    "width": 736,
    "height": 981
  }
};
